name: using_sqlalchemy
dependencies:
  - pip
  - python
  - pip:
      - mkdocs
      - mkdocs-material
      - pandas
      - psycopg2-binary
      - pytest-postgresql
      - pytest
      - sqlacodegen-v2
      - sqlalchemy
